meson: Write the correct path to the data in config.h (#220)
* add data install test

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -26,9 +26,11 @@ jobs:
   build:
     name: ${{ matrix.build.name }}
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
         build:
+        - name: data-install-test-gcc
+          os: ubuntu-22.04
         - name: ubuntu-22.04-gcc
           os: ubuntu-22.04
         - name: ubuntu-22.04-clang
@@ -39,6 +41,7 @@ jobs:
     runs-on: ${{ matrix.build.os }}
     env:
       NETPANZER_DATADIR: ${{ github.workspace }}/data
+      INST_PREFIX_DIR: ${{ github.workspace }}/inst_test
     steps:
     - uses: actions/checkout@v4
       with:
@@ -84,7 +87,7 @@ jobs:
 
     - name: Setup
       run: |
-        ./setup-build.sh _build -Dnls=$want_nls
+        ./setup-build.sh _build -Dprefix=$INST_PREFIX_DIR -Dnls=$want_nls
 
     - name: Meson build
       run: ninja -C _build
@@ -93,3 +96,15 @@ jobs:
       run: |
         cd _build
         meson test --suite=netpanzer -v
+
+    - name: Data install test
+      if: ${{ contains(matrix.build.name, 'data-install-test') }}
+      run: |
+        unset NETPANZER_DATADIR
+        cd _build
+        # want fail
+        $GITHUB_WORKSPACE/tests/test_data_install.sh || true
+        meson install --skip-subprojects
+        cd $INST_PREFIX_DIR/bin
+        # want pass
+        $GITHUB_WORKSPACE/tests/test_data_install.sh
